### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by Iey4iej3** [karino2/PngNote#10]
I suggest submitting the app to the F-Droid repo, both the Boox and non-Boox versions. [Here](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) is a tutorial.

**Comment by karino2** [comment]
These days, I do not have a spare time for managing further releases. May be in the future.

**Comment by igordsm** [comment]
@karino2 Would you be open to have others helping in a more active way in the project? I'm no android expert, but I could try and make a new release with the latest changes.

**Comment by karino2** [comment]
What do you mean? You are talking about releasing to F-Droid, right?
If it is possible that someone can help release binary to F-Droid, I'm grad to receive that help.

**Comment by igordsm** [comment]
Yeah, I'd like first to start by doing a new point release with the updates after 2021 and then submit a MR to inclusion in F-droid. I'll try and make the process reproducible so it's easier to release more often in the future.

**Comment by karino2** [comment]
OK, let's move on and we'll see what happens.
